<Project>
  <PropertyGroup>
    <Version>26.07.07</Version>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <Product>PKHeX</Product>
    <Company>Patrik Lleshaj</Company>
    <Authors>Patrik Lleshaj</Authors>
    <Copyright>Copyright © Patrik Lleshaj</Copyright>
    <SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyMMddHHmmss"))</SourceRevisionId>
    <!-- UI version for PKHeX.Avalonia releases (semver) -->
    <UIVersion>1.51.5</UIVersion>
  </PropertyGroup>
</Project>
