using System;
using static System.BitConverter; // float->uint conversion for legality messages
using static PKHeX.Core.LegalityCheckResultCode;
using static PKHeX.Core.CheckIdentifier;

namespace PKHeX.Core;

internal sealed class MiscVerifierPA8 : Verifier
{
    private static readonly LegendsArceusVerifier Arceus = new();

    protected override CheckIdentifier Identifier => Misc;

    public override void Verify(LegalityAnalysis data)
    {
        if (data.Entity is PA8 pk)
            Verify(data, pk);
    }

    internal void Verify(LegalityAnalysis data, PA8 pk)
    {
        Arceus.Verify(data);
        VerifyAbsoluteSizes(data, pk);
        MiscVerifierHelpers.VerifyStatAlignment(data, pk);
        MiscVerifierPK8.VerifyTechRecordFlags(data, pk); // copied from SW/SH via HOME
        FullnessRules.Verify(data, pk);

        var social = pk.Sociability;
        if (social != 0)
            data.AddLine(GetInvalid(Encounter, MemorySocialZero));

        if (!pk.IsBattleVersionValid(data.Info.EvoChainsAllGens))
            data.AddLine(GetInvalid(StatBattleVersionInvalid));

        if (pk.CanGigantamax)
            data.AddLine(GetInvalid(StatGigantamaxInvalid));

        if (pk.DynamaxLevel != 0)
            data.AddLine(GetInvalid(StatDynamaxInvalid));

        if (pk.GetMoveRecordFlagAny() && !pk.IsEgg) // already checked for eggs
            data.AddLine(GetInvalid(EggRelearnFlags));
    }


    internal static void VerifyAbsoluteSizes(LegalityAnalysis data, PA8 pk)
    {
        // Check if the size values are correct, with some edge cases where they are fixed and not calculated.
        // If not an edge case, must be calculated.

        // Eager return if it matches; flagging at the very end is not expensive at all.
        // Interacting with in Legends: Arceus will trigger a recalculation to the "correct" value.
        if (IsMatchCurrent(pk))
            return;

        // Since it doesn't match the in-game (re)calculated value, it must be one of the edge cases.
        if (IsAbsoluteEdgeCase(data, pk))
            return;

        // Must match. Flag any that mismatch.
        VerifyCalculatedSizes(data, pk);
    }

    private static bool IsAbsoluteEdgeCase(LegalityAnalysis data, PA8 pk)
    {
        var enc = data.EncounterMatch;

        // HOME 3.0.1+ fixes the "127" Height/Weight Alpha encounters to 255, but doesn't update the float calculated sizes.
        // Putting it in party and putting it back in box did trigger them to update, so it can legally be two states:
        // Mutated (255 with 127-based-floats), or Updated (255 with 255-based-floats)
        // Since most players won't be triggering an update, it is more likely that it is only mutated.
        // Check for mutated first. If not matching mutated, must match updated.
        if (enc is EncounterStatic8a { IsAlpha127: true }) 
            return IsMatch127(pk); // 127-127 and 255-255 can match 127.

        // Generated by HOME with hardcoded floats that don't correlate to any calculation (manual entry). Similar to LGP/E Meltan gift.
        if (enc is WA8 { Species: (ushort)Species.Enamorus })
            return IsEnamorusGiftUntouched(data, pk);

        // When creating Legends: Arceus side-data within HOME for anything not originating from Legends: Arceus, it calculates the absolute values in the app.
        // Starting in HOME 4.0.0, the app uses FMADD (Fused Multiply Add) for size calculations. Different results for 30 of 256 scalars compared to in-game step-by-step math.
        if (enc is { Context: not EntityContext.Gen8a } or EncounterSlot8GO && IsCalculatedHOME400(data, pk))
            return true;

        // Check for (=>)PLA=>HOME=>{other game, and evolve}=>HOME=>PLA, where the values can still match the pre-evolution.
        if (pk is IHomeTrack { HasTracker: true } && IsMatchPreEvolution(data, pk))
            return true;

        return false;
    }

    private static bool IsMatchPreEvolution(LegalityAnalysis data, PA8 pk)
    {
        // Imperfect, should check for if it has any purchased flags not accessible to this evolution stage. Whatever.
        // Also not checking for unavailable evolutions on other games, but this really isn't worth the effort.
        if (!IsAbsoluteRetainedPast(data))
            return false;

        // Check if any of the pre-evolutions match the in-game calculation.
        // If they were foreign transfers, they can match HOME's value if they were evolved later in another game.
        var evos = data.Info.EvoChainsAllGens.Gen8a;
        for (int i = 1; i < evos.Length; i++)
        {
            var evo = evos[i];
            var pi = PersonalTable.LA[evo.Species, evo.Form];
            if (IsMatchCurrent(pk, pi))
                return true;

            if (!pk.LA && IsMatchAbsoluteHOME400(pk, pi))
                return true;
        }

        return false;
    }

    private static bool IsCalculatedHOME400(LegalityAnalysis data, PA8 pk)
    {
        // Any interaction in-game triggers a re-calculation.
        if (IsAbsoluteRecalculated(data, pk))
            return false;

        // We could potentially weed out more by checking if it was required to evolve in this game, but not worth the effort.
        return IsMatchAbsoluteHOME400(pk);
    }

    private static bool IsEnamorusGiftUntouched(LegalityAnalysis data, PA8 pk)
    {
        if (IsAbsoluteRecalculated(data, pk))
            return false;
        // Can gain EVs in S/V, then transfer back to Legends: Arceus.

        return pk is { HeightAbsolute: WA8.EnamorusHeight, WeightAbsolute: WA8.EnamorusWeight };
    }

    private static bool IsAbsoluteRecalculated(LegalityAnalysis data, PA8 pk)
    {
        // Indicates that it was interacted with in Legends: Arceus.
        if (!data.IsStoredSlot(StorageSlotType.Box))
            return true;
        if (pk.PurchasedRecord.ContainsAnyExcept<byte>(0))
            return true;
        if (pk.RibbonHisui)
            return true;
        if (pk.HasUsedGrit)
            return true;
        if (pk.Status_Condition != 0)
            return true;
        return false;
    }

    private static bool IsAbsoluteRetainedPast(LegalityAnalysis data)
    {
        if (!data.IsStoredSlot(StorageSlotType.Box))
            return false;
        return true;
    }

    private static bool IsMatchCurrent(PA8 pk) => IsMatchCurrent(pk, pk.PersonalInfo);
    private static bool IsMatchAbsoluteHOME400(PA8 pk) => IsMatchAbsoluteHOME400(pk, pk.PersonalInfo);

    // ReSharper disable CompareOfFloatsByEqualityOperator -- THESE MUST MATCH EXACTLY
    private static void VerifyCalculatedSizes(LegalityAnalysis data, PA8 obj)
    {
        var expectHeight = obj.CalcHeightAbsolute;
        if (obj.HeightAbsolute != expectHeight)
            data.AddLine(GetInvalid(Encounter, StatIncorrectHeight, SingleToUInt32Bits(expectHeight)));

        var expectWeight = obj.CalcWeightAbsolute;
        if (obj.WeightAbsolute != expectWeight)
            data.AddLine(GetInvalid(Encounter, StatIncorrectWeight, SingleToUInt32Bits(expectWeight)));
    }

    // Static Alphas with 127 which were bumped to 255 and not yet updated in-game.
    private static bool IsMatch127(PA8 pk)
    {
        const byte scale = 127;
        var pi = pk.PersonalInfo;
        var expectHeight = PA8.GetHeightAbsolute(pi, scale);
        if (pk.HeightAbsolute != expectHeight)
            return false;

        var expectWeight = PA8.GetWeightAbsolute(pi, scale, scale);
        if (pk.WeightAbsolute != expectWeight)
            return false;

        return true;
    }

    // Recalculated in-game.
    private static bool IsMatchCurrent(PA8 pk, PersonalInfo8LA pi)
    {
        var expectHeight = PA8.GetHeightAbsolute(pi, pk.HeightScalar);
        if (pk.HeightAbsolute != expectHeight)
            return false;

        var expectWeight = PA8.GetWeightAbsolute(pi, pk.HeightScalar, pk.WeightScalar);
        if (pk.WeightAbsolute != expectWeight)
            return false;

        return true;
    }

    // Assigned on first entry via HOME 4.0.0 (can mismatch how the game normally calculates, since the game is not an optimized FMADD).
    private static bool IsMatchAbsoluteHOME400(PA8 pk, PersonalInfo8LA pi)
    {
        var expectHeight = PA8.GetHeightAbsoluteFused((ushort)pi.Height, pk.HeightScalar);
        if (pk.HeightAbsolute != expectHeight)
            return false;

        var expectWeight = PA8.GetWeightAbsoluteFused((ushort)pi.Weight, pk.HeightScalar, pk.WeightScalar);
        if (pk.WeightAbsolute != expectWeight)
            return false;

        return true;
    }
    // ReSharper restore CompareOfFloatsByEqualityOperator
}
