//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHeX.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHeX.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6th {
            get {
                object obj = ResourceManager.GetObject("_6th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alora {
            get {
                object obj = ResourceManager.GetObject("alora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alphaAZ {
            get {
                object obj = ResourceManager.GetObject("alphaAZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alphaZA {
            get {
                object obj = ResourceManager.GetObject("alphaZA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anti_pokerus_icon {
            get {
                object obj = ResourceManager.GetObject("anti_pokerus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bak {
            get {
                object obj = ResourceManager.GetObject("bak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_01 {
            get {
                object obj = ResourceManager.GetObject("box_mark_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_02 {
            get {
                object obj = ResourceManager.GetObject("box_mark_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_03 {
            get {
                object obj = ResourceManager.GetObject("box_mark_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_04 {
            get {
                object obj = ResourceManager.GetObject("box_mark_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_05 {
            get {
                object obj = ResourceManager.GetObject("box_mark_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_06 {
            get {
                object obj = ResourceManager.GetObject("box_mark_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_wp_clean {
            get {
                object obj = ResourceManager.GetObject("box_wp_clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_wp_default {
            get {
                object obj = ResourceManager.GetObject("box_wp_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKHeX - By Kaphotics
        ///http://projectpokemon.org/pkhex/
        ///
        ///19/12/26 - New Update:
        /// - Legality:
        /// - - Added: PP Count verification, Egg TR/StatNature checks, etc.
        /// - - Added: More static encounter locations.
        /// - - Added: Handling for downleveled raid content, and location crossover comparisons for wild encounters.
        /// - - Changed: Encounter yielding pattern for Gen8 is now slightly different from the one used for Gen5-7 (now yields more).
        /// - - Fixed: EvolutionTree regressions have been resolved. Please repor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crown {
            get {
                object obj = ResourceManager.GetObject("crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap date {
            get {
                object obj = ResourceManager.GetObject("date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dump {
            get {
                object obj = ResourceManager.GetObject("dump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_sm {
            get {
                object obj = ResourceManager.GetObject("fashion_f_sm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_sm_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_f_sm_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_uu {
            get {
                object obj = ResourceManager.GetObject("fashion_f_uu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_uu_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_f_uu_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_sm {
            get {
                object obj = ResourceManager.GetObject("fashion_m_sm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_sm_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_m_sm_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_uu {
            get {
                object obj = ResourceManager.GetObject("fashion_m_uu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_uu_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_m_uu_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_6 {
            get {
                object obj = ResourceManager.GetObject("gen_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_7 {
            get {
                object obj = ResourceManager.GetObject("gen_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_8 {
            get {
                object obj = ResourceManager.GetObject("gen_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_gg {
            get {
                object obj = ResourceManager.GetObject("gen_gg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_go {
            get {
                object obj = ResourceManager.GetObject("gen_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_vc {
            get {
                object obj = ResourceManager.GetObject("gen_vc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gift {
            get {
                object obj = ResourceManager.GetObject("gift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horohoro {
            get {
                object obj = ResourceManager.GetObject("horohoro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_favo {
            get {
                object obj = ResourceManager.GetObject("icon_favo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=Batch Editor
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///RibbonEditor=Ribbon Editor
        ///SAV_Apricorn=Apricorn Editor
        ///SAV_BerryField=Berry Field Viewer
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=Storage Viewer
        ///SAV_CGearSkin=C-Gear Skin
        ///SAV_Database=Database
        ///SAV_Encounters=Database
        ///SAV_EventFlags=Event Flag Editor
        ///SAV_EventReset1=Event Resetter
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=Folder List
        ///SAV_GameSelect=Game Selection
        ///SAV_Hal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=Batch Editor
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///RibbonEditor=Ribbon Editor
        ///SAV_Apricorn=Apricorn Editor
        ///SAV_BerryField=Berry Field Viewer
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=Storage Viewer
        ///SAV_CGearSkin=C-Gear Skin
        ///SAV_Database=Database
        ///SAV_Encounters=Database
        ///SAV_EventFlags=Event Flag Editor
        ///SAV_EventReset1=Event Resetter
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=Folder List
        ///SAV_GameSelect=Game Selection
        ///SAV_Hal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=Acerca de
        ///BatchEditor=Editor por lotes
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Editor de memorias / Poké Recreo
        ///RibbonEditor=Editor de cintas
        ///SAV_Apricorn=Editor de Bonguri
        ///SAV_BerryField=Visor de campos de bayas
        ///SAV_BoxLayout=Editor de fondos de cajas
        ///SAV_BoxList=Visor de almacenamiento
        ///SAV_CGearSkin=Editor de la apariencia C-Gear
        ///SAV_Database=Base de datos
        ///SAV_Encounters=Base de datos
        ///SAV_EventFlags=Editor de marca de eventos
        ///SAV_EventReset1=Reiniciador de eventos
        ///SAV_E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=À propos
        ///BatchEditor=Batch Editor
        ///ErrorWindow=Erreur
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///RibbonEditor=Rubans
        ///SAV_Apricorn=Noigrumes
        ///SAV_BerryField=Champs de Baies
        ///SAV_BoxLayout=Fonds de Boîtes
        ///SAV_BoxList=Storage Viewer
        ///SAV_CGearSkin=Fonds C-Gear
        ///SAV_Database=Base de Données
        ///SAV_Encounters=Database
        ///SAV_EventFlags=Événements dans le Jeu
        ///SAV_EventReset1=Réinitialisateur d&apos;événements
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=Liste Dossiers
        ///SAV_GameSelect=Choix  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=Batch Editor
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///RibbonEditor=Ribbon Editor
        ///SAV_Apricorn=Apricorn Editor
        ///SAV_BerryField=Berry Field Viewer
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=Storage Viewer
        ///SAV_CGearSkin=C-Gear Skin
        ///SAV_Database=Database
        ///SAV_Encounters=Database
        ///SAV_EventFlags=Event Flag Editor
        ///SAV_EventReset1=Event Resetter
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=Folder List
        ///SAV_GameSelect=Game Selection
        ///SAV_Hal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=バッチエディタ
        ///ErrorWindow=エラー
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=おもいで
        ///RibbonEditor=取得リボン
        ///SAV_Apricorn=ぼんぐり
        ///SAV_BerryField=きのみ畑
        ///SAV_BoxLayout=ボックスレイアウト
        ///SAV_BoxList=ボックスリスト
        ///SAV_CGearSkin=Cギア スキン
        ///SAV_Database=データベース
        ///SAV_Encounters=Database
        ///SAV_EventFlags=イベントフラグ
        ///SAV_EventReset1=イベントリセット
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=フォルダリスト
        ///SAV_GameSelect=ゲームバーション
        ///SAV_HallOfFame=殿堂入りデータ
        ///SAV_HallOfFame7=殿堂入りデータ参照
        ///SAV_HoneyTree=あまいかおりのするき
        ///SAV_Inventory=アイテム
        ///SAV_Link6=ポケモ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=Batch Editor
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///RibbonEditor=Ribbon Editor
        ///SAV_Apricorn=Apricorn Editor
        ///SAV_BerryField=Berry Field Viewer
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=Storage Viewer
        ///SAV_CGearSkin=C-Gear Skin
        ///SAV_Database=Database
        ///SAV_Encounters=Database
        ///SAV_EventFlags=Event Flag Editor
        ///SAV_EventReset1=Event Resetter
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=Folder List
        ///SAV_GameSelect=Game Selection
        ///SAV_Hal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=批量编辑器
        ///ErrorWindow=错误
        ///KChart=信息列表
        ///Main=PKHeX
        ///MemoryAmie=回忆/清爽乐
        ///RibbonEditor=奖章
        ///SAV_Apricorn=球果编辑
        ///SAV_BerryField=树果田查看器
        ///SAV_BoxLayout=盒子外观
        ///SAV_BoxList=寄放系统
        ///SAV_CGearSkin=C-装置皮肤
        ///SAV_Database=数据库
        ///SAV_Encounters=Database
        ///SAV_EventFlags=事件旗标编辑
        ///SAV_EventReset1=事件重置
        ///SAV_EventWork=Event Flag Editor
        ///SAV_FolderList=文件夹列表
        ///SAV_GameSelect=游戏选择
        ///SAV_HallOfFame=名人堂
        ///SAV_HallOfFame7=名人堂
        ///SAV_HoneyTree=甜甜蜜树编辑
        ///SAV_Inventory=物品栏
        ///SAV_Link6=宝可梦连接工具
        ///SAV_MailBox=邮箱编辑
        ///SAV_Misc3=训练家数据编辑        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap leaf {
            get {
                object obj = ResourceManager.GetObject("leaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nocheck {
            get {
                object obj = ResourceManager.GetObject("nocheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap numhilo {
            get {
                object obj = ResourceManager.GetObject("numhilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap numlohi {
            get {
                object obj = ResourceManager.GetObject("numlohi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap other {
            get {
                object obj = ResourceManager.GetObject("other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap party {
            get {
                object obj = ResourceManager.GetObject("party", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pgldings_normalregular {
            get {
                object obj = ResourceManager.GetObject("pgldings_normalregular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap qr {
            get {
                object obj = ResourceManager.GetObject("qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rare_icon {
            get {
                object obj = ResourceManager.GetObject("rare_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rare_icon_2 {
            get {
                object obj = ResourceManager.GetObject("rare_icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap savePKM {
            get {
                object obj = ResourceManager.GetObject("savePKM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveSAV {
            get {
                object obj = ResourceManager.GetObject("saveSAV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are having issues viewing certain symbols/text: Options -&gt; Unicode
        ///
        ///// Main Window
        ///
        ///CTRL-O: Open
        ///CTRL-S: Export PKM
        ///CTRL-E: Export SAV
        ///CTRL-B: Export BAK
        ///CTRL-Q: Quit
        ///
        ///CTRL-D: Open PKM Database
        ///CTRL-F: Open Folder List
        ///CTRL-G: Open Mystery Gift Database
        ///CTRL-N: Open Encounter Database
        ///CTRL-M: Open Batch Editor
        ///CTRL-R: Open Box Report
        ///CTRL-P: Open About PKHeX
        ///CTRL-T: Import Showdown Set
        ///CTRL-SHIFT-T: Export Showdown Set
        ///CTRL-SHIFT-S: Open Settings
        ///
        ///Control + Click on...
        ///- Species [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shortcuts {
            get {
                return ResourceManager.GetString("shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap showdown {
            get {
                object obj = ResourceManager.GetObject("showdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SplashIcon {
            get {
                object obj = ResourceManager.GetObject("SplashIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swapBox {
            get {
                object obj = ResourceManager.GetObject("swapBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap valhilo {
            get {
                object obj = ResourceManager.GetObject("valhilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap valid {
            get {
                object obj = ResourceManager.GetObject("valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vallohi {
            get {
                object obj = ResourceManager.GetObject("vallohi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vc {
            get {
                object obj = ResourceManager.GetObject("vc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wand {
            get {
                object obj = ResourceManager.GetObject("wand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warn {
            get {
                object obj = ResourceManager.GetObject("warn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
