//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHeX.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHeX.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6th {
            get {
                object obj = ResourceManager.GetObject("_6th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alora {
            get {
                object obj = ResourceManager.GetObject("alora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alpha {
            get {
                object obj = ResourceManager.GetObject("alpha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alphaAZ {
            get {
                object obj = ResourceManager.GetObject("alphaAZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alphaZA {
            get {
                object obj = ResourceManager.GetObject("alphaZA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anti_pokerus_icon {
            get {
                object obj = ResourceManager.GetObject("anti_pokerus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_balls {
            get {
                object obj = ResourceManager.GetObject("bag_balls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_battle {
            get {
                object obj = ResourceManager.GetObject("bag_battle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_berries {
            get {
                object obj = ResourceManager.GetObject("bag_berries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_candy {
            get {
                object obj = ResourceManager.GetObject("bag_candy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_free {
            get {
                object obj = ResourceManager.GetObject("bag_free", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_ingredient {
            get {
                object obj = ResourceManager.GetObject("bag_ingredient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_items {
            get {
                object obj = ResourceManager.GetObject("bag_items", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_key {
            get {
                object obj = ResourceManager.GetObject("bag_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_mail {
            get {
                object obj = ResourceManager.GetObject("bag_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_medicine {
            get {
                object obj = ResourceManager.GetObject("bag_medicine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_mega {
            get {
                object obj = ResourceManager.GetObject("bag_mega", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_pcitems {
            get {
                object obj = ResourceManager.GetObject("bag_pcitems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_tech {
            get {
                object obj = ResourceManager.GetObject("bag_tech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_treasure {
            get {
                object obj = ResourceManager.GetObject("bag_treasure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bag_z {
            get {
                object obj = ResourceManager.GetObject("bag_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bak {
            get {
                object obj = ResourceManager.GetObject("bak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_01 {
            get {
                object obj = ResourceManager.GetObject("box_mark_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_02 {
            get {
                object obj = ResourceManager.GetObject("box_mark_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_03 {
            get {
                object obj = ResourceManager.GetObject("box_mark_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_04 {
            get {
                object obj = ResourceManager.GetObject("box_mark_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_05 {
            get {
                object obj = ResourceManager.GetObject("box_mark_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_mark_06 {
            get {
                object obj = ResourceManager.GetObject("box_mark_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_wp_clean {
            get {
                object obj = ResourceManager.GetObject("box_wp_clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_wp_default {
            get {
                object obj = ResourceManager.GetObject("box_wp_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKHeX - By Kaphotics
        ///http://projectpokemon.org/pkhex/
        ///
        ///25/10/26 - New Update:
        /// - Added: Support for Legends: Z-A.
        /// - Legality:
        /// - - Initial handling for recognizing and generating encounters from Z-A.
        /// - - Please do not report issues with this release&apos;s handling with legality/encounters. We are aware of what still needs work.
        /// - Notes:
        /// - - All encounters can be traced back to an RNG seed.
        /// - - With multiple shiny rolls (wild only) or shinies, this calculation is not instant (&gt;15 seconds), so it i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crown {
            get {
                object obj = ResourceManager.GetObject("crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap date {
            get {
                object obj = ResourceManager.GetObject("date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dump {
            get {
                object obj = ResourceManager.GetObject("dump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_sm {
            get {
                object obj = ResourceManager.GetObject("fashion_f_sm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_sm_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_f_sm_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_uu {
            get {
                object obj = ResourceManager.GetObject("fashion_f_uu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_f_uu_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_f_uu_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_sm {
            get {
                object obj = ResourceManager.GetObject("fashion_m_sm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_sm_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_m_sm_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_uu {
            get {
                object obj = ResourceManager.GetObject("fashion_m_uu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fashion_m_uu_illegal {
            get {
                object obj = ResourceManager.GetObject("fashion_m_uu_illegal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_6 {
            get {
                object obj = ResourceManager.GetObject("gen_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_7 {
            get {
                object obj = ResourceManager.GetObject("gen_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_8 {
            get {
                object obj = ResourceManager.GetObject("gen_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_bs {
            get {
                object obj = ResourceManager.GetObject("gen_bs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_gg {
            get {
                object obj = ResourceManager.GetObject("gen_gg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_go {
            get {
                object obj = ResourceManager.GetObject("gen_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_la {
            get {
                object obj = ResourceManager.GetObject("gen_la", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_sv {
            get {
                object obj = ResourceManager.GetObject("gen_sv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_vc {
            get {
                object obj = ResourceManager.GetObject("gen_vc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gen_za {
            get {
                object obj = ResourceManager.GetObject("gen_za", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gender_0 {
            get {
                object obj = ResourceManager.GetObject("gender_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gender_1 {
            get {
                object obj = ResourceManager.GetObject("gender_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gender_2 {
            get {
                object obj = ResourceManager.GetObject("gender_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gift {
            get {
                object obj = ResourceManager.GetObject("gift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horohoro {
            get {
                object obj = ResourceManager.GetObject("horohoro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_btlrom {
            get {
                object obj = ResourceManager.GetObject("icon_btlrom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_favo {
            get {
                object obj = ResourceManager.GetObject("icon_favo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=Über
        ///BatchEditor=Batch Editor
        ///BoxExporter=Box Export
        ///ErrorWindow=Fehler
        ///KChart=Tabelle
        ///Main=PKHeX
        ///MemoryAmie=Erinnerung / Ami Editor
        ///MoveShopEditor=Attacken Tutor Editor
        ///RibbonEditor=Band Editor
        ///SAV_Apricorn=Aprikoko Editor
        ///SAV_BattlePass=Kampfpass Editor
        ///SAV_BerryFieldXY=Beerenfeld Ansicht
        ///SAV_BlockDump8=Spielstand Block Dump
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=PC Ansicht
        ///SAV_Capture7GG=Fang Statistik Editor
        ///SAV_Chatter=Chatter Editor
        ///SAV_Database=Datenbank
        ///SAV_DLC5=Generati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=Batch Editor
        ///BoxExporter=Box Export
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Memory / Amie Editor
        ///MoveShopEditor=Move Shop Editor
        ///RibbonEditor=Ribbon Editor
        ///SAV_Apricorn=Apricorn Editor
        ///SAV_BattlePass=Battle Pass Editor
        ///SAV_BerryFieldXY=Berry Field Viewer
        ///SAV_BlockDump8=Savedata Block Dump
        ///SAV_BoxLayout=Box Layout Editor
        ///SAV_BoxList=Storage Viewer
        ///SAV_Capture7GG=Capture Record Editor
        ///SAV_Chatter=Chatter Editor
        ///SAV_Database=Database
        ///SAV_DLC5=Generation 5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=Acerca de
        ///BatchEditor=Editor por Lotes
        ///BoxExporter=Exportar caja
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Editor de Memorias / Poké Recreo
        ///MoveShopEditor=Editor de la Tienda de Movimientos
        ///RibbonEditor=Editor de Cintas
        ///SAV_Apricorn=Editor de Bonguri
        ///SAV_BattlePass=Editor de pases de combate
        ///SAV_BerryFieldXY=Visor de Campos de Bayas
        ///SAV_BlockDump8=Respaldo de bloques
        ///SAV_BoxLayout=Editor de fondos de Cajas
        ///SAV_BoxList=Visor de Almacenamiento
        ///SAV_Capture7GG=Editor de Récord d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=Acerca de
        ///BatchEditor=Editor por Lotes
        ///BoxExporter=Exportar caja
        ///ErrorWindow=Error
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Editor de Memorias / Poké Recreo
        ///MoveShopEditor=Editor de la Tienda de Movimientos
        ///RibbonEditor=Editor de Cintas
        ///SAV_Apricorn=Editor de Bonguri
        ///SAV_BattlePass=Editor de pases de combate
        ///SAV_BerryFieldXY=Visor de Campos de Bayas
        ///SAV_BlockDump8=Respaldo de bloques
        ///SAV_BoxLayout=Editor de fondos de Cajas
        ///SAV_BoxList=Visor de Almacenamiento
        ///SAV_Capture7GG=Editor de Récord d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_es_419 {
            get {
                return ResourceManager.GetString("lang_es-419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=À propos
        ///BatchEditor=Éditeur en vrac
        ///BoxExporter=Export de boîtes
        ///ErrorWindow=Erreur
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Éditeur souvenir/ami
        ///MoveShopEditor=Éditeur de capacités
        ///RibbonEditor=Rubans
        ///SAV_Apricorn=Noigrumes
        ///SAV_BattlePass=Cartes de combat
        ///SAV_BerryFieldXY=Champs de Baies
        ///SAV_BlockDump8=Blocs de données
        ///SAV_BoxLayout=Fonds de Boîtes
        ///SAV_BoxList=Visualiseur de stockage
        ///SAV_Capture7GG=Capture Éditeur d&apos;enregistrement
        ///SAV_Chatter=Éditeur Babil
        ///SAV_Database=Base de Données
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=Info
        ///BatchEditor=Editor Batch
        ///BoxExporter=Box Export
        ///ErrorWindow=Errore
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=Editor Memorie / Poké Io e Te
        ///MoveShopEditor=Editor Negozio Mosse
        ///RibbonEditor=Editor Fiocchi
        ///SAV_Apricorn=Editor Ghicocche
        ///SAV_BattlePass=Editor Pass Lotta
        ///SAV_BerryFieldXY=Visualizzatore Campi di Bacche
        ///SAV_BlockDump8=Dump Blocchi di Salvataggio
        ///SAV_BoxLayout=Editor Disposizione Box
        ///SAV_BoxList=Visualizzatore Storage
        ///SAV_Capture7GG=Editor Record di Catture
        ///SAV_Chatter=Chatter E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=About
        ///BatchEditor=バッチエディタ
        ///BoxExporter=ボックスエクスポート
        ///ErrorWindow=エラー
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=おもいで
        ///MoveShopEditor=技教え
        ///RibbonEditor=取得リボン
        ///SAV_Apricorn=ぼんぐり
        ///SAV_BattlePass=バトルパス
        ///SAV_BerryFieldXY=きのみ畑
        ///SAV_BlockDump8=Savedata Block Dump
        ///SAV_BoxLayout=ボックスレイアウト
        ///SAV_BoxList=ボックスリスト
        ///SAV_Capture7GG=Capture Record Editor
        ///SAV_Chatter=おしゃべり
        ///SAV_Database=データベース
        ///SAV_DLC5=Generation 5 DLC I/O
        ///SAV_Encounters=データベース
        ///SAV_EventFlags=イベントフラグ
        ///SAV_EventReset1=イベントリセット
        ///SAV_EventWork=イベントフラグ
        ///SA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=정보
        ///BatchEditor=일괄 편집 도구
        ///BoxExporter=Box Export
        ///ErrorWindow=오류
        ///KChart=KChart
        ///Main=PKHeX
        ///MemoryAmie=기억 / 파를레 편집 도구
        ///MoveShopEditor=Move Shop Editor
        ///RibbonEditor=리본 편집 도구
        ///SAV_Apricorn=규토리 편집 도구
        ///SAV_BattlePass=Battle Pass Editor
        ///SAV_BerryFieldXY=나무열매 밭 뷰어
        ///SAV_BlockDump8=세이브 데이터 블록 덤프
        ///SAV_BoxLayout=박스 레이아웃 편집 도구
        ///SAV_BoxList=소지 공간 뷰어
        ///SAV_Capture7GG=Capture Record Editor
        ///SAV_Chatter=Chatter Editor
        ///SAV_Database=데이터베이스
        ///SAV_DLC5=Generation 5 DLC I/O
        ///SAV_Encounters=데이터베이스
        ///SAV_EventFlags=이벤트 플래 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=关于
        ///BatchEditor=批量编辑器
        ///BoxExporter=导出箱子
        ///ErrorWindow=错误
        ///KChart=信息列表
        ///Main=PKHeX
        ///MemoryAmie=回忆编辑器
        ///MoveShopEditor=招式商店编辑器
        ///RibbonEditor=奖章
        ///SAV_Apricorn=球果编辑
        ///SAV_BattlePass=对战通行证编辑
        ///SAV_BerryFieldXY=树果田查看器
        ///SAV_BlockDump8=存档转储
        ///SAV_BoxLayout=盒子外观
        ///SAV_BoxList=寄放系统
        ///SAV_Capture7GG=捕获记录编辑
        ///SAV_Chatter=语音编辑器
        ///SAV_Database=数据库
        ///SAV_DLC5=第五世代DLC工具
        ///SAV_Encounters=数据库
        ///SAV_EventFlags=事件旗标编辑
        ///SAV_EventReset1=事件重置
        ///SAV_EventWork=事件标志编辑器
        ///SAV_FlagWork8b=事件标志编辑器
        ///SAV_FolderList=文件夹列表
        ///SAV_Gear=装扮配件编辑器
        ///SAV_Ge [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_zh_Hans {
            get {
                return ResourceManager.GetString("lang_zh-Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About=關於
        ///BatchEditor=批量編輯器
        ///BoxExporter=Box Export
        ///ErrorWindow=錯誤
        ///KChart=信息清單
        ///Main=PKHeX
        ///MemoryAmie=回憶編輯器
        ///MoveShopEditor=招式商店編輯器
        ///RibbonEditor=獎章
        ///SAV_Apricorn=球果編輯
        ///SAV_BattlePass=Battle Pass Editor
        ///SAV_BerryFieldXY=樹果田檢視器
        ///SAV_BlockDump8=存檔轉儲
        ///SAV_BoxLayout=盒子外觀
        ///SAV_BoxList=寄放系統
        ///SAV_Capture7GG=捕獲記錄編輯
        ///SAV_Chatter=Chatter Editor
        ///SAV_Database=資料庫
        ///SAV_DLC5=Generation 5 DLC I/O
        ///SAV_Encounters=遇見資料庫
        ///SAV_EventFlags=事件旗標編輯
        ///SAV_EventReset1=事件重置
        ///SAV_EventWork=事件標誌編輯器
        ///SAV_FlagWork8b=事件標誌編輯器
        ///SAV_Fol [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_zh_Hant {
            get {
                return ResourceManager.GetString("lang_zh-Hant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap leaf {
            get {
                object obj = ResourceManager.GetObject("leaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nocheck {
            get {
                object obj = ResourceManager.GetObject("nocheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap numhilo {
            get {
                object obj = ResourceManager.GetObject("numhilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap numlohi {
            get {
                object obj = ResourceManager.GetObject("numlohi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap other {
            get {
                object obj = ResourceManager.GetObject("other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap party {
            get {
                object obj = ResourceManager.GetObject("party", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pgldings_normalregular {
            get {
                object obj = ResourceManager.GetObject("pgldings_normalregular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap qr {
            get {
                object obj = ResourceManager.GetObject("qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rare_icon {
            get {
                object obj = ResourceManager.GetObject("rare_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rare_icon_2 {
            get {
                object obj = ResourceManager.GetObject("rare_icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap research_bonus_points {
            get {
                object obj = ResourceManager.GetObject("research_bonus_points", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ribbon_affix_none {
            get {
                object obj = ResourceManager.GetObject("ribbon_affix_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap savePKM {
            get {
                object obj = ResourceManager.GetObject("savePKM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveSAV {
            get {
                object obj = ResourceManager.GetObject("saveSAV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are having issues viewing certain symbols/text: Options -&gt; Unicode
        ///
        ///// Main Window
        ///
        ///CTRL-O: Open
        ///CTRL-S: Export PKM
        ///CTRL-E: Export SAV
        ///CTRL-B: Export BAK
        ///CTRL-Q: Quit
        ///
        ///CTRL-D: Open PKM Database
        ///CTRL-F: Open Folder List
        ///CTRL-G: Open Mystery Gift Database
        ///CTRL-N: Open Encounter Database
        ///CTRL-M: Open Batch Editor
        ///CTRL-R: Open Box Report
        ///CTRL-P: Open About PKHeX
        ///CTRL-T: Import Showdown Set
        ///CTRL-SHIFT-T: Export Showdown Set
        ///CTRL-SHIFT-S: Open Settings
        ///
        ///Control + Click on...
        ///- Species [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shortcuts {
            get {
                return ResourceManager.GetString("shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap showdown {
            get {
                object obj = ResourceManager.GetObject("showdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swapBox {
            get {
                object obj = ResourceManager.GetObject("swapBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap valhilo {
            get {
                object obj = ResourceManager.GetObject("valhilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap valid {
            get {
                object obj = ResourceManager.GetObject("valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vallohi {
            get {
                object obj = ResourceManager.GetObject("vallohi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vc {
            get {
                object obj = ResourceManager.GetObject("vc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wand {
            get {
                object obj = ResourceManager.GetObject("wand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warn {
            get {
                object obj = ResourceManager.GetObject("warn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
