namespace PKHeX.Core;

public enum ToughWord4 : byte
{
    EarthTones = 0,
    Implant = 1,
    GoldenRatio = 2,
    Omnibus = 3,
    Starboard = 4,
    MoneyRate = 5,
    Resolution = 6,
    Cadenza = 7,
    Education = 8,
    Cubism = 9,
    CrossStitch = 10,
    Artery = 11,
    BoneDensity = 12,
    Gommage = 13,
    Streaming = 14,
    Conductivity = 15,
    Copyright = 16,
    TwoStep = 17,
    Contour = 18,
    Neutrino = 19,
    Howling = 20,
    Spreadsheet = 21,
    GMT = 22,
    Irritability = 23,
    Fractals = 24,
    Flambe = 25,
    StockPrices = 26,
    PHBalance = 27,
    Vector = 28,
    Polyphenol = 29,
    Ubiquitous = 30,
    REMSleep = 31,
}
