namespace PKHeX.Core
{
    public enum SlotType
    {
        Any,
        Grass,
        Rough_Terrain,
        Yellow_Flowers,
        Purple_Flowers,
        Red_Flowers,
        Surf,
        Old_Rod,
        Good_Rod,
        Super_Rod,
        Rock_Smash,
        Horde,
        FriendSafari,
        Special,
        SOS,
        Swarm,
        Headbutt,
        Pokeradar,
        HoneyTree,
        HiddenGrotto,
        BugContest,
        Grass_Safari,
        Surf_Safari,
        Old_Rod_Safari,
        Good_Rod_Safari,
        Super_Rod_Safari,
        Rock_Smash_Safari,
        Pokeradar_Safari
    }
}
