namespace PKHeX.Core;

public enum SAV7BlockIndex
{
    MyItem,
    Situation,
    RandomGroup,
    MyStatus,
    PokePartySave,
    EventWork,
    ZukanData,
    GtsData,
    UnionPokemon,
    Misc,
    FieldMenu,
    ConfigSave,
    GameTime,
    BOX,
    BoxPokemon,
    ResortSave,
    PlayTime,
    FieldMoveModelSave,
    Fashion,
    JoinFestaPersonalSave1,
    JoinFestaPersonalSave2,
    JoinFestaDataSave,
    BerrySpot,
    FishingSpot,
    LiveMatchData,
    BattleSpotData,
    PokeFinderSave,
    MysteryGiftSave,
    Record,
    ValidationSave,
    GameSyncSave,
    PokeDiarySave,
    BattleInstSave,
    Sodateya,
    WeatherSave,
    QRReaderSaveData,
    TurtleSalmonSave,

    // Ultra Sun/Ultra Moon only
    BattleFesSave,
    FinderStudioSave,
}
