using System;

namespace PKHeX.Core;

public enum Decoration3 : byte
{
    NONE,
    SMALL_DESK,
    POKEMON_DESK,
    HEAVY_DESK,
    RAGGED_DESK,
    COMFORT_DESK,
    PRETTY_DESK,
    BRICK_DESK,
    CAMP_DESK,
    HARD_DESK,
    SMALL_CHAIR,
    POKEMON_CHAIR,
    HEAVY_CHAIR,
    PRETTY_CHAIR,
    COMFORT_CHAIR,
    RAGGED_CHAIR,
    BRICK_CHAIR,
    CAMP_CHAIR,
    HARD_CHAIR,
    RED_PLANT,
    TROPICAL_PLANT,
    PRETTY_FLOWERS,
    COLORFUL_PLANT,
    BIG_PLANT,
    GORGEOUS_PLANT,
    RED_BRICK,
    YELLOW_BRICK,
    BLUE_BRICK,
    RED_BALLOON,
    BLUE_BALLOON,
    YELLOW_BALLOON,
    RED_TENT,
    BLUE_TENT,
    SOLID_BOARD,
    SLIDE,
    FENCE_LENGTH,
    FENCE_WIDTH,
    TIRE,
    STAND,
    MUD_BALL,
    BREAKABLE_DOOR,
    SAND_ORNAMENT,
    SILVER_SHIELD,
    GOLD_SHIELD,
    GLASS_ORNAMENT,
    TV,
    ROUND_TV,
    CUTE_TV,
    GLITTER_MAT,
    JUMP_MAT,
    SPIN_MAT,
    C_LOW_NOTE_MAT,
    D_NOTE_MAT,
    E_NOTE_MAT,
    F_NOTE_MAT,
    G_NOTE_MAT,
    A_NOTE_MAT,
    B_NOTE_MAT,
    C_HIGH_NOTE_MAT,
    SURF_MAT,
    THUNDER_MAT,
    FIRE_BLAST_MAT,
    POWDER_SNOW_MAT,
    ATTRACT_MAT,
    FISSURE_MAT,
    SPIKES_MAT,
    BALL_POSTER,
    GREEN_POSTER,
    RED_POSTER,
    BLUE_POSTER,
    CUTE_POSTER,
    PIKA_POSTER,
    LONG_POSTER,
    SEA_POSTER,
    SKY_POSTER,
    KISS_POSTER,
    PICHU_DOLL,
    PIKACHU_DOLL,
    MARILL_DOLL,
    TOGEPI_DOLL,
    CYNDAQUIL_DOLL,
    CHIKORITA_DOLL,
    TOTODILE_DOLL,
    JIGGLYPUFF_DOLL,
    MEOWTH_DOLL,
    CLEFAIRY_DOLL,
    DITTO_DOLL,
    SMOOCHUM_DOLL,
    TREECKO_DOLL,
    TORCHIC_DOLL,
    MUDKIP_DOLL,
    DUSKULL_DOLL,
    WYNAUT_DOLL,
    BALTOY_DOLL,
    KECLEON_DOLL,
    AZURILL_DOLL,
    SKITTY_DOLL,
    SWABLU_DOLL,
    GULPIN_DOLL,
    LOTAD_DOLL,
    SEEDOT_DOLL,
    PIKA_CUSHION,
    ROUND_CUSHION,
    KISS_CUSHION,
    ZIGZAG_CUSHION,
    SPIN_CUSHION,
    DIAMOND_CUSHION,
    BALL_CUSHION,
    GRASS_CUSHION,
    FIRE_CUSHION,
    WATER_CUSHION,
    SNORLAX_DOLL,
    RHYDON_DOLL,
    LAPRAS_DOLL,
    VENUSAUR_DOLL,
    CHARIZARD_DOLL,
    BLASTOISE_DOLL,
    WAILMER_DOLL,
    REGIROCK_DOLL,
    REGICE_DOLL,
    REGISTEEL_DOLL,
}

public enum DecorationCategory3 : byte
{
    Desk,
    Chair,
    Plant,
    Ornament,
    Mat,
    Poster,
    Doll,
    Cushion,
}

public static class DecorationInfo
{
    public static DecorationCategory3 GetCategory(this Decoration3 deco) => deco switch
    {
        <= Decoration3.HARD_DESK      => DecorationCategory3.Desk,
        <= Decoration3.HARD_CHAIR     => DecorationCategory3.Chair,
        <= Decoration3.GORGEOUS_PLANT => DecorationCategory3.Plant,
        <= Decoration3.CUTE_TV        => DecorationCategory3.Ornament,
        <= Decoration3.SPIKES_MAT     => DecorationCategory3.Mat,
        <= Decoration3.KISS_POSTER    => DecorationCategory3.Poster,
        <= Decoration3.SEEDOT_DOLL    => DecorationCategory3.Doll,
        <= Decoration3.WATER_CUSHION  => DecorationCategory3.Cushion,
        <= Decoration3.REGISTEEL_DOLL => DecorationCategory3.Doll,
        _ => throw new ArgumentOutOfRangeException(nameof(deco)),
    };
}
