namespace PKHeX.Core;

public enum TrendyWord3E : byte
{
    KTHXBYE = 0,
    YESSIR = 1,
    AVANTGARDE = 2,
    COUPLE = 3,
    MUCHOBLIGED = 4,
    YEEHAW = 5,
    MEGA = 6,
    ONEHITKO = 7,
    DESTINY = 8,
    CANCEL = 9,
    NEW = 10,
    FLATTEN = 11,
    KIDDING = 12,
    LOSER = 13,
    LOSING = 14,
    HAPPENING = 15,
    HIPAND = 16,
    SHAKE = 17,
    SHADY = 18,
    UPBEAT = 19,
    MODERN = 20,
    SMELLYA = 21,
    BANG = 22,
    KNOCKOUT = 23,
    HASSLE = 24,
    WINNER = 25,
    FEVER = 26,
    WANNABE = 27,
    BABY = 28,
    HEART = 29,
    OLD = 30,
    YOUNG = 31,
    UGLY = 32,
}
